config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "prototypes#index"

  scope module: :prototypes do
    resources :popular, only: :index
    resources :newest, only: :index
  end

  resources :prototypes do
    scope module: :prototypes do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: :create
    end
  end

  resources :users, only: [:index, :show, :edit, :update]
  resources :tags, only: [:index, :show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :prototype
  belongs_to :user
  validates :text, presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/protoimage.rb
class Protoimage < ActiveRecord::Base
  mount_uploader :thumbnail, ProtoimageUploader

  enum role: %w(main sub)

  belongs_to :user
  belongs_to :prototype

  validates :role,
            inclusion: {in: Protoimage.roles.keys}

  validates :thumbnail, presence: true
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base

  belongs_to :user
  has_many :protoimages, dependent: :delete_all
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  accepts_nested_attributes_for :protoimages, allow_destroy: true

  acts_as_taggable

  def liked_by(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, UserimageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nickname, presence: true
  has_many :prototypes
  has_many :likes
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile, :member, :work, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :profile, :member, :work, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_proto, only: :create

  def create
    @proto.comments.create(comment_params)
    @comments = @proto.comments
  end

  private
  def set_proto
    @proto = Prototype.find(params[:prototype_id])
  end

  def comment_params
    params.require(:comment).permit(:id, :text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_proto

  def create
    @proto.likes.create(like_params)
  end

  def destroy
    @proto.likes.find_by(prototype_id: params[:prototype_id], user_id: current_user).destroy
    @proto.reload
  end

  private
    def set_proto
      @proto = Prototype.find(params[:prototype_id])
    end

    def like_params
      params.permit(
        prototype_id: params[:prototype_id]).merge(user_id: current_user.id)
    end
end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController
  before_action :set_proto, only: :create

  def create
    @proto.comments.create(comment_params)
    @comments = @proto.comments
  end

  private
  def set_proto
    @proto = Prototype.find(params[:prototype_id])
  end

  def comment_params
    params.require(:comment).permit(:id, :text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end

end

app/controllers/prototypes/likes_controller.rb
class Prototypes::LikesController < ApplicationController
  before_action :set_proto, only: [:create, :destroy]

  def create
    @proto.likes.create(like_params)
  end

  def destroy
    @proto.likes.find_by(prototype_id: params[:prototype_id], user_id: current_user).destroy
    @proto.reload
  end

  private
  def set_proto
    @proto = Prototype.find(params[:prototype_id])
  end

  def like_params
    params.permit(
      prototype_id: params[:prototype_id]).merge(user_id: current_user.id)
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController

  def index
    @protos = Prototype.includes(:user).order('created_at DESC').page(params[:page]).per(12)
  end

end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController

  def index
    @protos = Prototype.eager_load(:user).order("likes_count DESC").page(params[:page]).per(12)
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :set_proto, except: [:index, :new, :create]

  def index
    @protos = Prototype.includes(:user).order("RAND()").page(params[:page]).per(13)
  end

  def show
    @user = @proto.user
    @images = @proto.protoimages
    @comments = @proto.comments.includes(:prototype)
    @comment = @proto.comments.new(prototype_id: @proto.id) if user_signed_in?
    @tags = @proto.tags
  end

  def new
    @proto = Prototype.new
    @proto.protoimages.build
  end

  def create
    @proto = current_user.prototypes.new(proto_params)
    if @proto.save
      redirect_to root_path, notice: 'Your prototype has created successfully.'
    else
      flash.now[:alert] = 'Error: Please Fill in all blanks !'
      render :new
    end
  end

  def edit
    @subs = @proto.protoimages.sub
  end

  def update
    if @proto.update(proto_params)
      redirect_to prototype_path(@proto), notice: 'Your prototype has updated successfully.'
    else
      flash.now[:alert] = 'Error: Please Fill in all blank form !'
      render :edit
    end
  end

  def destroy
    @proto.destroy
    redirect_to root_path, notice: 'Your prototype has just deleted.'
  end

  private
    def set_proto
      @proto = Prototype.find(params[:id])
    end

    def proto_params
      params.require(:prototype).permit( \
        :title,
        :catch_copy,
        :concept,
        protoimages_attributes:[
          :id,
          :thumbnail,
          :role,
          :prototype_id,
          :_destroy]).merge(
          tag_list: params[:prototype][:tag])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @protos = Prototype.tagged_with(@tag).includes(:user).order('created_at DESC').page(params[:page]).per(12)
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, except: :show
before_action :set_user, only: [:show, :edit, :update]

  def show
    @protos = @user.prototypes.order('created_at DESC').page(params[:page]).per(12)
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user, notice: "ユーザー情報が更新されました。"
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :profile, :member, :work, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class_for(name)
    "active" if  name == params[:controller]
  end
end

app/helpers/form_helper.rb
module FormHelper
  def set_prototype(prototype)
    if prototype.new_record?
      prototype.protoimages.new(role: :main)
    end

    image_space_count = 2
    posting_image_count = prototype.protoimages.sub.size
    if posting_image_count < image_space_count
      (image_space_count - posting_image_count).times do
        prototype.protoimages.new(role: :sub)
      end
    end
    prototype
  end
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  %div{class: "alert alert-#{name == "notice" ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = msg

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2016.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
              =current_user.nickname
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                =link_to 'My page', user_path(current_user)
              %li
                = link_to 'Profile edit', edit_user_path(current_user)
              %li
                = link_to 'Sign out', destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'NEW PROTO', new_prototype_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
          .btn.btn-primary.navbar-btn
            =link_to 'GET STARTED', new_user_session_path

app/views/layouts/_main_visual.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{class: active_class_for('prototypes/popular')}
          = link_to 'Popular PROTO', popular_index_path
        %li{class:  active_class_for('prototypes/newest')}
          = link_to 'Newest PROTO', newest_index_path
      = link_to 'View Tags', tags_path,type:' button', class:'btn btn-default col-lg-1'

app/views/layouts/_prototypes.html.haml
.container.proto-list
  .row
    - protos.each do |proto|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          = link_to image_tag(proto.protoimages.main.first.thumbnail), prototype_path(proto)
          .caption
            %h3
              = link_to proto.title, prototype_path(proto)
            .proto-meta
              .proto-user
                = link_to "by #{proto.user.nickname}", user_path(proto.user)
              .proto-user.text-right
                = link_to 'delete', prototype_path(proto), method: :delete
              .proto-posted
                = proto.created_at.strftime('%b %d')
            %ul.proto-tag-list.list-inline
              - proto.tags.each do |tag|
                %li
                  = link_to tag.name, tag_path(tag), class: "btn btn-default"
  .text-center
    = paginate(protos)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = render "layouts/flash"
    = yield
    = render "layouts/footer"

app/views/prototypes/_comment.html.haml
.media
  .media-left
    - if comment.user.avatar?
      = link_to image_tag(comment.user.avatar, {alt: "64x64", "data-holder-rendered": "true",style: "width: 64px; height: 64px;", class: 'media-object' }), user_path(comment.user)
    - else
      %img.media-object{alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
  .media-body
    %h4#top-aligned-media.media-heading
      = link_to comment.user.nickname, user_path(comment.user), class: 'anchorjs-link'

      %a.anchorjs-link{href: "#top-aligned-media"}
        %span.anchorjs-icon
    = comment.text

app/views/prototypes/_image_form.html.haml
%li.list-group-item.col-md-4
  .image-upload.js-preview-images

app/views/prototypes/_like.html.haml
- if user_signed_in?
  - if proto.liked_by(current_user)
    = button_to prototype_like_path(proto.id, current_user), method: :delete, class: 'btn btn-default', remote: true do
      = image_tag("icon_heart_red.svg")
      LIKE
      = @proto.likes_count
  - else
    = button_to prototype_likes_path(proto.id, current_user), method: :post, class:'btn btn-default', remote: true do
      = image_tag("icon_heart.svg")
      LIKE
      = @proto.likes_count
- else
  = button_tag class: 'btn btn-default' do
    = image_tag("icon_heart.svg")
    LIKE
    = @proto.likes_count

app/views/prototypes/comments/create.js.haml
$('#js-text-area').val('')
$('#js-render-comments').html("#{ j(render partial: 'prototypes/comment', collection: @comments)}");
$('#js-comment-counts').html("(#{ @comments.count})" )

app/views/prototypes/edit.html.haml
.container.proto-new{action: ""}
  = form_for @proto do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, class: 'proto-new-title', placeholder: 'Title'
      .row
        .col-md-12
          .cover-image-upload.js-preview-images
            = f.fields_for :protoimages, @proto.protoimages.main[0] do |i|
              = i.file_field :thumbnail
              = i.hidden_field :role, value: :main
          .col-md-12
            %ul.proto-sub-list.list-group
              = f.fields_for :protoimages, @subs do |i|
                %li.list-group-item.col-md-4
                  .image-upload.js-preview-images
                    = i.file_field :thumbnail
                    = i.hidden_field :role, value: :sub
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: 'Catch Copy'
        .col-md-12
          = f.text_area :concept, cols: '30', rows: '4', placeholder: 'Concept'
        .col-md-12
          %h4 Tag List
          .row
            - 3.times do
              .col-md-3
                = text_field_tag "prototype[tag][]", "", placeholder: "Val"
      .row.text-center.proto-btn
        = f.submit 'UPDATE', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/index.html.haml
= render 'layouts/main_visual'
= render partial: 'layouts/prototypes', locals: { protos: @protos }

app/views/prototypes/likes/create.js.haml
$("#like-button").html("#{ j(render partial: 'prototypes/like', locals: { proto: @proto })}");

app/views/prototypes/likes/destroy.js.haml
:plain
  $("#like-button").html(
    "#{ j(render partial: 'prototypes/like', locals: {proto: @proto})}"
    );

app/views/prototypes/new.html.haml
.container.proto-new{action: ""}
  = form_for @proto do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, class: 'proto-new-title', placeholder: 'Title'
      .row
        .col-md-12
          .cover-image-upload.js-preview-images
            = f.fields_for :protoimages do |i|
              = i.file_field :thumbnail, class: 'img img-responstive'
              = i.hidden_field :role, value: "main"
          .col-md-12
            %ul.proto-sub-list.list-group
              - 3.times do
                = f.fields_for :protoimages do |i|
                  %li.list-group-item.col-md-4
                    .image-upload.js-preview-images
                      = i.file_field :thumbnail
                      = i.hidden_field :role, value: "sub"
              / %li.list-group-item.col-md-4
              /   .image-upload-plus
              /     %span + JS時に使用
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: 'Catch Copy'
        .col-md-12
          = f.text_area :concept, cols: '30', rows: '4', placeholder: 'Concept'
        .col-md-12
          %h4 Tag List
          .row
            - 3.times do
              .col-md-3
                = text_field_tag "prototype[tag][]", "", placeholder: "Val"
      .row.text-center.proto-btn
        = f.submit 'Publish', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          - if @user.avatar?
            = link_to image_tag(@user.avatar, {class:'media-object', alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64",style: "width: 64px; height: 64px;"}), user_path(@user)
          - else
            = link_to image_tag("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==",  {class:'media-object', alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64",style: "width: 64px; height: 64px;"})
        .media-body
          %h4#top-aligned-media.media-heading
            = @proto.title
            = link_to 'edit', edit_prototype_path(@proto), class:'btn btn-xs navbar-inverse'
            = link_to 'delete', prototype_path(@proto), method: :delete, class: 'btn btn-xs navbar-inverse btn-delete'
          .proto-user
            = link_to "by #{@user.nickname}", user_path(@user)
            %p.degree
              = @user.member
              ／
              = @user.work
    .col-md-6.text-right
      #like-button
        =render partial: 'like', locals: { proto: @proto }
  .row
    .col-md-9
      = image_tag(@images.main.first.thumbnail, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        %li.list-group-item
          = image_tag(@images.sub.first.thumbnail, class: 'img-responsive')
        %li.list-group-item
          = image_tag(@images.sub.second.thumbnail, class: 'img-responsive')
        %li.list-group-item
          = image_tag(@images.sub.third.thumbnail, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @proto.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @proto.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        -@tags.each do |tag|
          %li
            =link_to tag.name, tag_path(tag),  class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num#js-comment-counts
        = "(#{@comments.count})"
    .col-md-8#js-render-comments
      = render partial: 'comment', collection: @comments
    = form_for [@proto, @comment], class: 'form-inline', remote: true do |f|
      %h4.col-md-12 Write a comment
      .row
        .form-group.col-md-7
          = f.text_area :text, class: 'form-control', rows: '3', placeholder: 'Your comments', id: 'js-text-area'
        .form-group.col-md-5
          = f.submit 'Comment', class:'btn btn-primary'

app/views/tags/index.html.haml
= render 'layouts/main_visual'
.container.proto-list
  .row
    - @tags.each do |tag|
      -if tag.taggings_count >= 1
        .col-sm-4.col-md-3.proto-content
          .thumbnail
            = link_to tag.name, tag_path(tag.id), class: 'btn btn-tag'
            .tag-meta
              = link_to "#{tag.taggings_count}Projects", tag_path(tag.id), class:'label label-default tag-list-number'

app/views/tags/show.html.haml
= render 'layouts/main_visual'
.container
  .row
    .col-sm-12.proto-list
      .thumbnail
        = button_tag @tag.name, class:'btn btn-tag'
        .tag-meta
          = link_to "#{@tag.taggings_count}Projects", tag_path(@tag.id), class:'label label-default tag-list-number'

= render partial: 'layouts/prototypes', locals: { protos: @protos }

app/views/users/edit.html.haml
.container.user-new
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :nickname, placeholder: 'Username', autofocus: true
            .user-image.col-md-2.js-preview-images
              = button_tag 'Change Image', class: 'btn btn-primary'
              = f.file_field :avatar
          = f.email_field :email, placeholder: "E-Mail", class: 'user-email'
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :member, placeholder: ''
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, cols: '30', rows: '4', placeholder: 'Profile'
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :work, cols: '30', rows: '4', placeholder: 'Works'
      .row.text-center.user-btn
        = f.submit 'Save', class: 'btn btn-lg btn-primary btn-block'

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        - if @user.avatar?
          = link_to image_tag(@user.avatar,  {class:'media-object', alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64",style: "width: 64px; height: 64px;"})
        - else
          = link_to image_tag("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", {class:'media-object', alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64",style: "width: 64px; height: 64px;"})
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.nickname
          %span.label.label-default.project-number
            = @user.prototypes.length
            %i Projects
        .proto-user
          %span.degree
            = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p
              = @user.profile
          .col-md-6
            %h4 Works
            %p
              = @user.work


= render partial: 'layouts/prototypes', locals: { protos: @protos }

/ .text-center
/   %ul.pagination
/     %li.disabled
/       %a{"aria-label": "Previous", href: "#"}
/         %span{"aria-hidden": "true"} «
/     %li.active
/       %a{href: "#"}
/         1
/         %span.sr-only (current)
/     %li
/       %a{href: "#"} 2
/     %li
/       %a{href: "#"} 3
/     %li
/       %a{href: "#"} 4
/     %li
/       %a{href: "#"} 5
/     %li
/       %a{"aria-label": "Next", href: "#"}
/         %span{"aria-hidden": "true"} »